In [1]:
import torch

##  1 𝐓𝐞𝐧𝐬𝐨𝐫 减法实验

In [2]:
M = torch.rand(1, 3)
N = torch.rand(2, 1)
M, N

(tensor([[0.5765, 0.3713, 0.5624]]),
 tensor([[0.9063],
         [0.5366]]))

In [3]:
print("sub1-", M-N)
print("sub2-", torch.sub(M, N)) # M, N都被广播成 2*3 的格式，再对应相减
M.sub_(N)   # 引用操作，改变M值。
            # 报错原因：因为是inplace操作，所以不会将M进行广播，出现矩阵大小不匹配的错误
print("sub2-", M)

sub1- tensor([[-0.3298, -0.5350, -0.3438],
        [ 0.0399, -0.1653,  0.0258]])
sub2- tensor([[-0.3298, -0.5350, -0.3438],
        [ 0.0399, -0.1653,  0.0258]])


RuntimeError: output with shape [1, 3] doesn't match the broadcast shape [2, 3]

## 2 𝐓𝐞𝐧𝐬𝐨𝐫 正态、转置、内积

### 2.1 构造正态分布

### 2.1 

In [14]:
P = torch.normal(mean=0, std=0.01, size=(3, 2))
Q = torch.normal(mean=0, std=0.01, size=(4, 2))
P, Q

(tensor([[-0.0117,  0.0019],
         [-0.0040,  0.0106],
         [-0.0209,  0.0020]]),
 tensor([[-0.0021, -0.0022],
         [ 0.0319,  0.0053],
         [ 0.0056,  0.0121],
         [ 0.0126,  0.0056]]))

In [41]:
print(Q)
Q.transpose_(0, 1)  # inplace操作
print(Q)
#torch.transpose(Q, 0, 1) #开辟新的空间存储
#print(Q)

tensor([[-0.0021, -0.0022],
        [ 0.0319,  0.0053],
        [ 0.0056,  0.0121],
        [ 0.0126,  0.0056]])
tensor([[-0.0021,  0.0319,  0.0056,  0.0126],
        [-0.0022,  0.0053,  0.0121,  0.0056]])


### 2.3 内积

In [46]:
print(P.size(), Q.size())
torch.mm(P, Q)

torch.Size([3, 2]) torch.Size([2, 4])


tensor([[ 2.0887e-05, -3.6251e-04, -4.1631e-05, -1.3667e-04],
        [-1.4171e-05, -7.2213e-05,  1.0596e-04,  8.7576e-06],
        [ 4.0387e-05, -6.5469e-04, -9.1791e-05, -2.5206e-04]])

### 2.2 转置