In [1]:
import torch

In [2]:
x = torch.empty(5, 3)
x

tensor([[8.4490e-39, 1.0102e-38, 1.0561e-38],
        [1.0286e-38, 1.0653e-38, 1.0469e-38],
        [9.5510e-39, 9.9184e-39, 9.0000e-39],
        [1.0561e-38, 1.0653e-38, 4.1327e-39],
        [8.9082e-39, 9.8265e-39, 9.4592e-39]])

In [5]:
x = torch.ones(2, 2, requires_grad=True)

In [7]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [8]:
y = x + 2

In [9]:
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [10]:
y.requires_grad

True