In [1]:
import mxnet as mx

In [2]:
from mxnet import nd

In [3]:
x = nd.arange(12)

In [4]:
x


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

In [5]:
x.shape

(12,)

In [6]:
x.size

12

In [7]:
X = x.reshape((3, 4))

In [8]:
X


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [9]:
x.shape

(12,)

In [10]:
X.shape

(3, 4)

In [11]:
nd.zeros((2, 3, 4))


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<NDArray 2x3x4 @cpu(0)>

In [12]:
nd.ones((3, 4))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

In [13]:
nd.random.normal(0, 1, shape=(3, 4))


[[ 1.1630785   0.4838046   0.29956347  0.15302546]
 [-1.1688148   1.5580711  -0.5459446  -2.3556297 ]
 [ 0.5414402   2.6785066   1.2546345  -0.54877394]]
<NDArray 3x4 @cpu(0)>

In [16]:
X[1:2, :] = 12

In [17]:
X


[[ 0.  1.  2.  3.]
 [12. 12. 12. 12.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [18]:
before = id(X)
X = X + X
id(X) == before

False

In [19]:
X


[[ 0.  2.  4.  6.]
 [24. 24. 24. 24.]
 [16. 18. 20. 22.]]
<NDArray 3x4 @cpu(0)>

In [20]:
#减少内存开销
before = id(X)
nd.elemwise_add(X, X, out=X)
id(X) == before

True

In [21]:
X[:] == X + X


[[1. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>

In [22]:
X


[[ 0.  4.  8. 12.]
 [48. 48. 48. 48.]
 [32. 36. 40. 44.]]
<NDArray 3x4 @cpu(0)>

In [23]:
before = id(X)
X[:] = X + X
id(X) == before

True

In [24]:
X


[[ 0.  8. 16. 24.]
 [96. 96. 96. 96.]
 [64. 72. 80. 88.]]
<NDArray 3x4 @cpu(0)>

In [25]:
X += X
id(X) == before

True

In [26]:
from mxnet import autograd, nd

In [27]:
x = nd.arange(4).reshape((4, 1))

In [28]:
x


[[0.]
 [1.]
 [2.]
 [3.]]
<NDArray 4x1 @cpu(0)>

In [29]:
x.attach_grad()

In [30]:
with autograd.record():
    y = 2 * nd.dot(x.T, x)

In [31]:
y


[[28.]]
<NDArray 1x1 @cpu(0)>

In [32]:
y.backward()

In [33]:
y


[[28.]]
<NDArray 1x1 @cpu(0)>

In [34]:
assert (x.grad - 4 * x).norm().asscalar() == 0

In [35]:
x.grad


[[ 0.]
 [ 4.]
 [ 8.]
 [12.]]
<NDArray 4x1 @cpu(0)>

In [36]:
(x.grad - 4 * x).norm().asscalar() == 0

True

In [37]:
autograd.is_training()

False

In [39]:
with autograd.record():
    print(autograd.is_training())

True


In [40]:
def f(a):
    b = a * 2
    while b.norm().asscalar() < 1000:
        b = b * 2
    if b.sum().asscalar() > 0:
        c = b
    else:
        c = b * 100
    return c

In [47]:
a = nd.random.normal(shape=(2, 3))
a.attach_grad()
with autograd.record():
    c = f(a)
c.backward()

In [48]:
a.grad


[[51200. 51200. 51200.]
 [51200. 51200. 51200.]]
<NDArray 2x3 @cpu(0)>

In [49]:
c


[[  -6928.171   19314.24    21000.42 ]
 [  29248.932 -141207.69    55105.535]]
<NDArray 2x3 @cpu(0)>

In [50]:
a


[[-0.13531584  0.37723127  0.41016445]
 [ 0.5712682  -2.7579627   1.07628   ]]
<NDArray 2x3 @cpu(0)>

In [51]:
c/a


[[51200.    51199.996 51200.   ]
 [51200.    51200.    51200.   ]]
<NDArray 2x3 @cpu(0)>

In [52]:
nd.random.uniform?

Signature:
nd.random.uniform(
    low=0,
    high=1,
    shape=_Null,
    dtype=_Null,
    ctx=None,
    out=None,
    **kwargs,
)
Docstring:
Draw random samples from a uniform distribution.

Samples are uniformly distributed over the half-open interval *[low, high)*
(includes *low*, but excludes *high*).

Parameters
----------
low : float or NDArray, optional
    Lower boundary of the output interval. All values generated will be
    greater than or equal to low. The default value is 0.
high : float or NDArray, optional
    Upper boundary of the output interval. All values generated will be
    less than high. The default value is 1.0.
shape : int or tuple of ints, optional
    The number of samples to draw. If shape is, e.g., `(m, n)` and `low` and
    `high` are scalars, output shape will be `(m, n)`. If `low` and `high`
    are NDArrays with shape, e.g., `(x, y)`, then output will have shape
    `(x, y, m, n)`, where `m*n` samples are drawn for each `[low, high)` pair.
dtype : {'fl

In [53]:
nd.random.uniform??

Signature:
nd.random.uniform(
    low=0,
    high=1,
    shape=_Null,
    dtype=_Null,
    ctx=None,
    out=None,
    **kwargs,
)
Source:   
def uniform(low=0, high=1, shape=_Null, dtype=_Null, ctx=None, out=None, **kwargs):
    """Draw random samples from a uniform distribution.

    Samples are uniformly distributed over the half-open interval *[low, high)*
    (includes *low*, but excludes *high*).

    Parameters
    ----------
    low : float or NDArray, optional
        Lower boundary of the output interval. All values generated will be
        greater than or equal to low. The default value is 0.
    high : float or NDArray, optional
        Upper boundary of the output interval. All values generated will be
        less than high. The default value is 1.0.
    shape : int or tuple of ints, optional
        The number of samples to draw. If shape is, e.g., `(m, n)` and `low` and
        `high` are scalars, output shape will be `(m, n)`. If `low` and `high`
        are NDArrays 